# Generated by Django 5.0.6 on 2026-06-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubCrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('budget_cents', models.PositiveIntegerField(help_text='Total budget for the crawl, in US cents')),
                ('mode', models.CharField(choices=[('walking', 'Walking'), ('transit', 'Transit'), ('driving', 'Driving'), ('bicycling', 'Bicycling')], default='walking', max_length=16)),
                ('total_distance_m', models.PositiveIntegerField(default=0)),
                ('total_duration_sec', models.PositiveIntegerField(default=0)),
                ('total_cost_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crawls_starting_here', to='bars.bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='0-indexed position within the crawl')),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('cost_cents', models.PositiveIntegerField(default=0, help_text='Travel cost (e.g. subway fare); does not include drinks')),
                ('polyline', models.TextField(blank=True, help_text='Encoded polyline string from the routing API')),
                ('from_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_starting_here', to='bars.bar')),
                ('to_bar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs_ending_here', to='bars.bar')),
                ('crawl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='crawls.pubcrawl')),
            ],
            options={
                'ordering': ['crawl', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='crawlleg',
            constraint=models.UniqueConstraint(fields=('crawl', 'order'), name='unique_crawl_leg_order'),
        ),
    ]
